export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpg",
    username: "Jacky",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpg",
    username: "Ayleen",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpg",
    username: "Alex Durden",
  },
  {
    id: 4,
    profilePicture: "assets/person/noAvatar.jpg",
    username: "Paul ED",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.webp",
    username: "Lisa",
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpg",
    username: "Coach Esume",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpeg",
    username: "Tom Brady",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpg",
    username: "Lena",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpg",
    username: "Zoe",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpg",
    username: "Zendaya",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Hamburg, meine Perle💙",
    photo: "assets/post/1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/post/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    photo: "assets/post/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc: "My last SuperBowl",
    photo: "assets/post/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "MATCHDAY 🏐🏆",
    photo: "assets/post/9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpg",
    desc: "Never regret anything that made you smile.",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
